### ISSUE TITLE
Issue with date. It does't recognise today date correctly or it works on other time zone 

### ISSUE THREAD

**Issue by zuwf** [zoreet/habit-tracker#7] opened 2023-12-26 19:16 UTC
![Screenshot from 2023-12-27 00-39-17](https://github.com/zoreet/habit-tracker/assets/130776416/f1d473c6-c044-497e-bc89-a94fb0a86b01)
![Screenshot from 2023-12-27 00-38-31](https://github.com/zoreet/habit-tracker/assets/130776416/4655f5aa-e834-4de4-be25-a89cbddf0abd)

Today's date is 27-12-23 I filled those checks on 25th and 26th but it showing on 27th. on rechecking by removing and checking again , the checks are inserted with yesterday's date on the habit file. but dots are shown in today's date in query file

**Comment by zoreet** [comment] 2023-12-27 08:25
This is a weird one. Will need to investigate...

**Comment by zuwf** [comment] 2023-12-27 10:51
> This is a weird one. Will need to investigate...

I tested with other device and changed the timezones.. and found that it follows GMT and ours was GMT + 5.30

**Comment by zoreet** [comment] 2023-12-28 09:00
Thanks. This narrows it down for me. Will work on a fix asap

**Comment by zoreet** [comment] 2023-12-29 09:41
This should be fixed with https://github.com/zoreet/habit-tracker/releases/tag/1.1.2 

Could you pls give it a test and confirm it's working now?

**Comment by zuwf** [comment] 2023-12-30 07:27
No , It become even more buggy. The current date is fixed with 30-12-2023, and checking date fixed with 29th constantly. It not changed by at any point , I tried by changing my mobile's date and time a week forward, still the checking date is same and result in the query page stuck with 30th, in general it not actually detects the device time and date

**Comment by zoreet** [comment] 2023-12-31 13:50
This is SO weird. I'll try to test this with a colleague that leaves in your timezone. If they're not available, would you mind jumping on a call with me? I'd like to share some debug code with you to understand what's happening. The reason why I'm puzzled is because before I was definitely following GMT ( by mistake ), but with the current it _should_ work OK.

**Comment by ganser8** [comment] 2024-01-01 11:39
Hi there! Happy New Year!

I have the same bug in Linux but on Android everything is OK. GMT+4.

**Comment by timbruls** [comment] 2024-01-02 09:36
Hi, Same issue here, on MacOS,

**Comment by zoreet** [comment] 2024-01-03 11:12
I managed to reproduce the bug and pushed [version 1.1.4](https://github.com/zoreet/habit-tracker/releases/tag/1.1.4) with a fix. Can you please test it and let me know if it works?

**Comment by ganser8** [comment] 2024-01-03 13:45
It works! Thanks a lot!

**Comment by timbruls** [comment] 2024-01-03 14:34
Works here as well, thank you very much for the fast fix.

**Comment by zuwf** [comment] 2024-01-03 14:58
Still having the GMT issue, I tested by setting upcoming dates in my device with 12.01 AM , the checks I made during that time creating entries in previous day. But changing the time by 5.30 AM I am able to check with the actual date I set on my device

**Comment by zoreet** [comment] 2024-01-03 19:48
@zuwf can you join my discord https://discord.gg/RVG3DRF4 and help me reproduce and fix this once and for all?

**Comment by zoreet** [comment] 2024-01-03 20:19
Found one last piece of the puzzle. I was using [toISOString](`https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString`) to convert a Date object to `YYYY-MM-DD` and this uses the UTC timezone always.

Released [1.1.5](https://github.com/zoreet/habit-tracker/releases/tag/1.1.5) which fixes this. Thank you @zuwf for details on how to reproduce, and the patience to keep on testing.

**Comment by zoreet** [comment] 2024-01-03 20:23
Re-released 1.1.5 because it still had some debug code in it

**Comment by zuwf** [comment] 2024-01-03 20:33
> Re-released 1.1.5 because it still had some debug code in it

Thank you 😬😇 , Working fine for me now..
I didn't got the re-release yet.. if it corrects the following date data showing on the habits row.. It's become perfect 
![Screenshot_20240105-000302.png](https://github.com/zoreet/habit-tracker/assets/130776416/1df911c7-3e11-4924-9d9d-8f3ee1d6bc5c)

**Comment by zuwf** [comment] 2024-01-03 20:34
> Re-released 1.1.5 because it still had some debug code in it

Thank you 😬😇 , Working fine for me now..
I didn't got the re-release yet.. if it corrects the following date data showing on the habits row.. It's become perfect

![Screenshot_20240105-000239.png](https://github.com/zoreet/habit-tracker/assets/130776416/b7cb69fd-b3d0-42e6-ada4-aad7d7f7240b)

**Closed** 2024-01-03 21:58 UTC
Labels: bug
